version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    links:
      - db
    ports:
      - "5001:5001"
    entrypoint: /OpenPortScanner/bin/boot.sh
    volumes:
      - .:/OPS
  db:
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_DATABASE: OPS
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "32000:3306"
#     volumes:
#       - ./data:/var/lib/mysql
  worker:
    build: .
    entrypoint: /OpenPortScanner/bin/worker.sh
    depends_on:
      - redis
  monitor:
    build: .
    ports:
      - "5555:5555"
    entrypoint: /OpenPortScanner/bin/monitor.sh
    depends_on:
      - redis
  redis:
    image: redis