version: "2"
services:
  app:
    build: ./
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/OPS
  db:
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_DATABASE: OPS
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "32000:3306"
#    volumes:
#      - ./db:/docker-entrypoint-initdb.d/:ro