version: "2"

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    links:
      - db
    ports:
      - "5001:5001"
    entrypoint: /OpenPortScanner/bin/boot.sh
    volumes:
      - .:/OPS
  db:
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_DATABASE: OPS
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "32000:3306"
#     volumes:
#       - ./data:/var/lib/mysql
  worker:
    build: .
    entrypoint: /OpenPortScanner/bin/worker.sh
    depends_on:
      - redis
  monitor:
    build: .
    ports:
      - "5555:5555"
    entrypoint: /OpenPortScanner/bin/monitor.sh
    depends_on:
      - redis
  redis:
    image: redis
  prometheus-OPS:
    image: prom/prometheus
    container_name: prometheus-OPS
    volumes:
      - ./app/prometheus:/etc/prometheus:ro
      - prometheus_data:/prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    expose:
      - 9090
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus-OPS
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar