"""devices

Revision ID: 7b8fad355f33
Revises: 38ad92811038
Create Date: 2020-03-09 14:58:20.031619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8fad355f33'
down_revision = '38ad92811038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_host', table_name='devices')
    op.drop_index('ix_devices_ip', table_name='devices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_devices_ip', 'devices', ['ip'], unique=False)
    op.create_index('ix_devices_host', 'devices', ['host'], unique=False)
    # ### end Alembic commands ###
